//Atoms Key
export const TOTAL_SCORE_STATE = 'TOTAL_SCORE_STATE';
export const SCORE_STATE       = 'SCORE_STATE';
export const CURRENT_BATSMAN_STATE = 'CURRENT_BATSMAN_RUNS_STATE';
export const CURRENT_BOWLER_STATE = 'CURRENT_BOWLER_STATE';
export const CURRENT_BATTING_TEAM_STATE = 'CURRENT_BATTING_TEAM_STATE';
export const TEAM_ONE_STATE = 'TEAM_ONE';
export const TEAM_TWO_STATE = 'TEAM_TWO';
export const POPUP_OPEN_STATE = 'POPUP_OPEN_STATE';
export const POPUP_STATE = 'POPUP_STATE';
export const CURRENT_BOWLING_TEAM_STATE = 'CURRENT_BOWLING_TEAM_STATE';
export const OVERS_STATE = 'OVERS_STATE';


//Selectors key
export const INITIAL_POPUPS_STATE = 'INITIAL_POPUPS_STATE';
